### ISSUE TITLE
static resources

### ISSUE THREAD

**Issue by enzodev** [vouill/vue-slideout#10]
Hi, if I don't want use npm can you give me install instructions and static resources (vue-slideout.js, css files ...) to include in our project?

**Comment by vouill** [comment]
Hey !

You can still download it as zip https://github.com/vouill/vue-slideout/archive/master.zip . 
Then you can access the lib with:
`import Slideout from 'path-to-vue-slideout/lib/vue-slideout.js'`

This plugins also works on the assumption that you have slideout.js in your dependencies. 
(it performs a require('slideout')).
In a normal setup its performed w/ dev dependencies, since you do not use npm you probably need to import it too.

What is your setup if you are not using npm if i may ask?

**Comment by vouill** [comment]
Closing this issue since no updates
