### ISSUE TITLE
can't scroll slider down

### ISSUE THREAD

**Issue by bubnenkoff** [vouill/vue-slideout#3]
I have slider that higher than screen size. I need to scroll its down. But I can't do it.

**Comment by vouill** [comment]
Can you provide a demo, I'll look into it? Have you checked the original repo issues? It looks like it's css related.

**Comment by bubnenkoff** [comment]
http://test1.code123.org/ 
I checked it on iPhone, but I can't scroll it's down also in Chrome (iPhone browser emulation)

**Comment by vouill** [comment]
add `overflow-y: scroll;` to the `.slideout-menu` class

**Comment by bubnenkoff** [comment]
Thanks! But Could you check demo abode again. it's seems for me that it works a little bit buggy. Try to scroll green part, than touch left up, down, than green again and left again. 

On my devise after several times when I am touching left side right side begin moving.

**Comment by vouill** [comment]
i tried messing with it but i cant get your moving issue. maybe its just a css scrolling isssue ?

**Comment by bubnenkoff** [comment]
You tried om test1.code123.org ? And it's work fine for you?

**Comment by vouill** [comment]
yes

**Comment by vouill** [comment]
in most cases, it's simply a css issue, height smaller than window, scroll not well handled, ill close this issue for now since it doesnt seems to be javascript related. checkout the original slideout repo issues you might find your issue.

**Comment by vouill** [comment]
I see it now on a bigger screen, ill see what i can do

**Comment by bubnenkoff** [comment]
Oh Good! Thanks! Am I right that it's js related issue?

**Comment by vouill** [comment]
I think it css related.

**Comment by vouill** [comment]
I see where it comes from. Checkout slideoutjs [demo](https://slideout.js.org/).
Now open chrome dev tool and inspect body, a `body : { overflow: hidden }` prevent the scroll to propagate on the main when the side menu is open. Remove it and you have your current state. I would say if you want to have the menu always shown and still being able to scroll your panel, you need find to tweek the css.

A possible solution is to use slideout for mobile only (in the slideout repo its treated how to) and use a more basic layout to handle dual scroll layout  for desktop like [this for example](http://codepen.io/vouill/pen/evJNdK)  ( many other way to do it btw ). 
Anyway since it is css related i am closing this issue.( you can ask on the original repo too )

**Comment by bubnenkoff** [comment]
Where I should to remove it? From `node_modules\slideout\index.css` ? and than do 
`npm run build`?

**Comment by vouill** [comment]
In your own css, do not touch the library css.
